//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EDM : DbContext
    {
        public EDM()
            : base("name=EDM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<devices> devices { get; set; }
        public virtual DbSet<logs> logs { get; set; }
        public virtual DbSet<owners> owners { get; set; }
        public virtual DbSet<transactions> transactions { get; set; }
    
        public virtual ObjectResult<GetLastOfEach_Result> GetLastOfEach()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLastOfEach_Result>("GetLastOfEach");
        }
    }
}
