//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class logs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public logs()
        {
            this.transactions = new HashSet<transactions>();
        }
    
        public int id { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public string annotation { get; set; }
        public int satellites { get; set; }
        public decimal altitude { get; set; }
        public decimal speed { get; set; }
        public decimal accuracy { get; set; }
        public decimal direction { get; set; }
        public string provider { get; set; }
        public System.DateTime time_utc { get; set; }
        public decimal battery { get; set; }
        public string androidid { get; set; }
        public string serial { get; set; }
        public string url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transactions> transactions { get; set; }
    }
}
