//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactions
    {
        public int id { get; set; }
        public int devices_id { get; set; }
        public int logs_id { get; set; }
        public int owners_id { get; set; }
        public System.DateTime date_time { get; set; }
    
        public virtual devices devices { get; set; }
        public virtual logs logs { get; set; }
        public virtual owners owners { get; set; }
    }
}
